A variety of minor cleanups
rust-embedded/embedonomicon pull request #92
Opened 2024-08-28 19:09 UTC by noncombatant

Fix some typos, Markdown, `rustfmt`, and use a (necessary) double dash for `--version`.

2024-08-28 19:37 UTC, BartMassey requested changes
This looks good — thanks much for the contribution. I've suggested a few changes…

2024-08-28 19:37 UTC, BartMassey commented on src/asm.md
> +operations like context switching, etc., that require assembly.
"operations, for example context switching, that require assembly."

2024-08-28 19:37 UTC, BartMassey commented on src/dma.md
> +To prevent these problematic reorderings we can use a [`compiler_fence`]:
":" should be "."?

2024-08-28 19:37 UTC, BartMassey commented on src/logging.md
> +> command from before (`qemu-system-arm -cpu ... -kernel ...`) in the Cargo
Use ellipsis … instead of three dots here, I think.

2024-08-28 19:37 UTC, BartMassey commented on src/logging.md
> +binary I/O; that is, send the addresses to the host as bytes rather than as
"binary I/O: send the addresses"

2024-08-28 21:11 UTC, noncombatant commented
Thanks! I've incorporated your suggestions.

2024-08-29 03:01 UTC, BartMassey approved these changes
Thanks!

2024-08-29 08:00 UTC, eldruin reviewed
Thank you for this change.
However, the CI seems broken. I opened #93.

2025-05-20 18:48 UTC, adamgreig approved these changes

2025-05-20 18:58 UTC, merged